import type { Metadata } from 'next'
import { Overpass } from 'next/font/google'
import './globals.css'

const overpass = Overpass({ subsets: ['cyrillic'] })

export const metadata: Metadata = {
  title: 'КВІТКА - керамічна студія',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="uk">
      <body className={overpass.className}>{children}</body>
    </html>
  )
}
